# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 473456761341bb6d6a19ec4b67573d5d72cdd54828fcac6a9fc2c5b2183d27f2ea136c267d387842bf00f122dd408f0a776d9a965d51f36c27505df6edef214b

test:
  secret_key_base: a31deba6fe725e28cd6bbe56268d9eaf6c04fae706cf841c70aba83bc381a52d73452077bf7a3450aea9efaf4097b578fad0f4f9a2ea3020733549a0832d5c14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
